# A configuration file for our Quality Infrastructure builds: https://wiki.gpii.net/w/Quality_Infrastructure
email: tony@raisingthefloor.org
env_runtime: linux-desktop

apps:
  - app_name: gpii-location-bar-relay
    git_repository: https://github.com/the-t-in-rtf/gpii-location-bar-relay.git
    git_branch: GPII-1791
    software_stack: nodejs
    software_stack_version: lts
    folder:
      dest: /app/gpii-location-bar-relay
    run_in: fedora
    deploy: false
    setup:
      - yarn install
    test_cmds:
      - PATH=$PATH:/home/vagrant/sync/node_modules/chromedriver/bin/chromedriver/ BROWSERS=chrome yarn test